package com.example.bean;

public enum FilterCondition {
	
		CONTAINS, CONTAINS_CASE_SENSITIVE, DOES_NOT_CONTAIN, DOES_NOT_CONTAIN_CASE_SENSITIVE, EQUAL,EQUAL_CASE_SENSITIVE, NOT_EQUAL, NOT_EQUAL_CASE_SENSITIVE, GREATER_THAN, GREATER_THAN_OR_EQUAL, LESS_THAN, LESS_THAN_OR_EQUAL, STARTS_WITH,STARTS_WITH_CASE_SENSITIVE, ENDS_WITH,ENDS_WITH_CASE_SENSITIVE, NULL, NOT_NULL,EMPTY, NOT_EMPTY
}
